apiVersion: v1
kind: Service
metadata:
  name: himarket-server
  labels:
    app: himarket-server
spec:
  type: {{ .Values.server.service.type }}
  ports:
    - port: {{ .Values.server.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: himarket-server
