apiVersion: v1
kind: Service
metadata:
  name: himarket-frontend
  labels:
    app: himarket-frontend
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: himarket-frontend
