name: 🐛 Bug Report
description: Report a bug to help us improve HiMarket
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug! Please fill out the information below to help us diagnose and fix the issue quickly.
        
        **Before submitting:**
        - Search existing issues to avoid duplicates
        - Make sure you're using the latest version
        - Check the documentation and FAQ

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: When I try to..., the system...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: I expected...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened (include error messages if any)
      placeholder: Instead, what happened was...
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Affected Component
      description: Which part of HiMarket is affected?
      options:
        - Frontend (User Interface)
        - Admin Console
        - Backend API
        - Database (DAL)
        - Configuration/Setup
        - Documentation
        - CI/CD Pipeline
        - Other
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Critical (System crash, data loss)
        - High (Major functionality broken)
        - Medium (Feature partially works)
        - Low (Minor issue, workaround exists)
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Your environment details
      placeholder: |
        - OS: [e.g. macOS 13.0, Ubuntu 22.04, Windows 11]
        - Browser: [e.g. Chrome 120, Safari 17, Firefox 121]
        - HiMarket Version: [e.g. v1.0.0, commit hash]
        - Java Version: [e.g. OpenJDK 17]
        - Node.js Version: [e.g. v20.0.0]
      render: markdown
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs and Error Messages
      description: Paste any relevant log output or error messages
      placeholder: |
        Paste error logs here...
      render: shell
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem
      placeholder: Drag and drop images here or paste image URLs
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context about the problem
      placeholder: This started happening after...
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I have included all necessary information above
          required: true
        - label: I am using the latest version of HiMarket
          required: false
        - label: I can reproduce this issue consistently
          required: false

