apiVersion: v1
kind: Service
metadata:
  name: nacos
  labels:
    app: nacos
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: console
    - port: 8848
      targetPort: 8848
      protocol: TCP
      name: api
    - port: 9848
      targetPort: 9848
      protocol: TCP
      name: grpc
  selector:
    app: nacos
